version: '3.4'

services:
  nginx:
    depends_on:
      - frontend
      - products
      - carts
      - orders
      - auth
      - dataprep
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80'
  dataprep:
    image: ${DOCKER_REGISTRY-}datapreparer
    ports:
      - '5000:5000'
    environment:
      - STORAGE_BASE_URL=https://simpleecom.blob.core.windows.net/awesomeeshop
      - PRODUCTS_BASE_URL=http://products
    build:
      context: ./prepdata
      dockerfile: Dockerfile
  frontend:
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_HOMEPAGE_PIC=https://simpleecom.blob.core.windows.net/awesomeeshop/eshop_homepage.png
      - REACT_APP_API_BASE_URL=

    build:
      context: ./frontend
      dockerfile: Dockerfile
  products:
    image: ${DOCKER_REGISTRY-}simpleecomproductsapi
    ports:
      - '8084:80'
    build:
      context: .
      dockerfile: Simpleecom.Products.API/Dockerfile

  carts:
    image: ${DOCKER_REGISTRY-}simpleecomcartsapi
    ports:
      - '8085:80'
    build:
      context: .
      dockerfile: Simpleecom.Cart.API/Dockerfile

  orders:
    image: ${DOCKER_REGISTRY-}simpleecomordersapi
    ports:
      - '8082:80'
    build:
      context: .
      dockerfile: Simpleecom.Orders.API/Simpleecom.Orders.API/Dockerfile

  auth:
    image: ${DOCKER_REGISTRY-}simpleecomauth
    ports:
      - '8083:80'
    build:
      context: .
      dockerfile: Simpleecom.Auth/Dockerfile
