version: '3.4'

services:
  nginx:
    depends_on:
      - frontend
      - products
      - carts
      - orders
      - auth
      - dataprep
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80'
  dataprep:
    image: ${DOCKER_REGISTRY-}datapreparer
    ports:
      - '5000:5000'
    environment:
      - STORAGE_BASE_URL=https://simpleecom.blob.core.windows.net/awesomeeshop
      - PRODUCTS_BASE_URL=http://products
    build:
      context: ./prepdata
      dockerfile: Dockerfile
  frontend:
    ports:
      - '3001:3000'
    environment:
      - REACT_APP_HOMEPAGE_PIC=https://simpleecom.blob.core.windows.net/awesomeeshop/eshop_homepage.png
      - REACT_APP_API_BASE_URL=none
      - REACT_APP_SERVER_NAME=Test
    build:
      context: ./frontend
      dockerfile: Dockerfile
  products:
    image: ${DOCKER_REGISTRY-}simpleecomproductsapi
    ports:
      - '8084:80'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - COSMOSDBOPTIONS__DATABASE_ID=Simpleecom
      - COSMOSDBOPTIONS__PARTITION_KEY=/brand
      - COSMOSDBOPTIONS__CONTAINER_NAME=Products
      - COSMOSDBOPTIONS__COSMOS_ENDPOINT=
      - COSMOSDBOPTIONS__CONNECTION_STRING=
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    build:
      context: .
      dockerfile: Simpleecom.Products.API/Dockerfile

  carts:
    image: ${DOCKER_REGISTRY-}simpleecomcartsapi
    ports:
      - '8085:80'
    environment:
      - COSMOSDBOPTIONS__DATABASE_ID=Simpleecom
      - COSMOSDBOPTIONS__PARTITION_KEY=/userId
      - COSMOSDBOPTIONS__CONTAINER_NAME=Carts
      - COSMOSDBOPTIONS__COSMOS_ENDPOINT=
      - COSMOSDBOPTIONS__CONNECTION_STRING=
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    build:
      context: .
      dockerfile: Simpleecom.Cart.API/Dockerfile

  orders:
    image: ${DOCKER_REGISTRY-}simpleecomordersapi
    ports:
      - '8082:80'
    environment:
      - COSMOSDBOPTIONS__DATABASE_ID=Simpleecom
      - COSMOSDBOPTIONS__PARTITION_KEY=/userId
      - COSMOSDBOPTIONS__CONTAINER_NAME=Orders
      - COSMOSDBOPTIONS__COSMOS_ENDPOINT=
      - COSMOSDBOPTIONS__CONNECTION_STRING=
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    build:
      context: .
      dockerfile: Simpleecom.Orders.API/Simpleecom.Orders.API/Dockerfile

  auth:
    image: ${DOCKER_REGISTRY-}simpleecomauth
    ports:
      - '8083:80'
    environment:
      - COSMOSDBOPTIONS__DATABASE_ID=Simpleecom
      - COSMOSDBOPTIONS__PARTITION_KEY=/email
      - COSMOSDBOPTIONS__CONTAINER_NAME=Users
      - COSMOSDBOPTIONS__COSMOS_ENDPOINT=
      - COSMOSDBOPTIONS__CONNECTION_STRING=
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    build:
      context: .
      dockerfile: Simpleecom.Auth/Dockerfile
